apiVersion: 1

datasources:
  - name: samm-prometheus
    type: prometheus
    uid: c3a5e98c-6e94-44b8-b894-ae05241051b7
    url: http://mimir:8080/prometheus
    access: proxy
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: samana
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.44.0
    cacheLevel: 'High'
    disableRecordingRules: false
    incrementalQueryOverlapWindow: 10m
  - name: samm-loki
    type: loki
    uid: a3b388bb-5990-45ca-a5b5-0bca47387fe1
    url: http://loki:3100
    access: proxy
    jsonData:
      timeout: 60
      maxLines: 1000
  - uid: "fe37eb96-e778-4098-b04d-bf73e9683d48"
    orgId: 1
    name: samm-config
    type: "yesoreyeram-infinity-datasource"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      global_queries: []
    readOnly: false